services:
  portal-api:
    image: f4lk0n/fkn:${COMPOSE_PREFIX}portal-api
    container_name: ${COMPOSE_PREFIX}portal-api
    hostname: portal-api
    build:
      context: ./.docker
      args:
        - ARG_TIMEZONE=${PROJECT_TIMEZONE}
    volumes:
      # Data
      - ./..data/:/data/
      # Logs
      - ./..logs/:/logs/
      # Applications
      - ./src/:/src/
    networks:
      frontend:
        ipv4_address: 172.21.0.120
      backend:
        ipv4_address: 172.20.0.120
    expose:
      # Server
      - "80"
      - "443"
      # XDebug
      - "9003"

networks:
  frontend:
    driver: bridge
    name: ${COMPOSE_PREFIX}frontend
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
  backend:
    driver: bridge
    name: ${COMPOSE_PREFIX}backend
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
